name: Save Action

on:
  workflow_dispatch:
 # schedule:
 # - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://coyote-point-wind.herokuapp.com/api/wind
